trigger: none
pool:
  vmImage: "ubuntu-latest"
# pool:
#   name: $(poolName)
 - stage: terraform_plan
    jobs:
    - deployment: terraform_plan
      displayName: terraform_plan
      environment: 'terraform_plan'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: ../template/template.yml
            - checkout: git:///some git repo
            - script: |
                cd $(Build.SourcesDirectory)/Infra
                terraform init --upgrade 
                terraform plan
## terraform apply stage, where it applies the changes real/current state of the infrastructure in order to achieve the desired state
## In this stage terraform wait for manual approvals 
  - stage: terraform_apply
    jobs:
    - deployment: terraform_apply
      displayName: terraform_apply
      environment: 'terraform_apply'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: ../template/template.yml
            - checkout: git:///some repo
            - script: |
                cd $(Build.SourcesDirectory)/Infra
                terraform init --upgrade 
                terraform apply -auto-approve
            - task: DeleteFiles@1
              inputs:
                SourceFolder: true
                Contents: '*'
